apiVersion: v1

kind: Pod

metadata:
  name: my-pod-nginx

spec:
  containers:
    - name: my-nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP

    - name: ubuntu-sidecar-container
      image: ubuntu:latest
      command: ["tail"]
      args: ["-f", "/dev/null"]