apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: my-replicaSet-nginx

spec:
  # ReplicaSet 정의
  replicas: 4
  selector:
    matchLabels:
      app: my-pod-nginx-label  # 중요
  # Pod 정의
  template:
    metadata:
      name: my-pod-nginx
      labels:
        app: my-pod-nginx-label  # 중요
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
