# LB 타입의 서비스는 AWS, GCP, Azure 와 같은 클라우드에서만 생성 가능.

apiVersion: v1

kind: Service

metadata:
  name: my-svc-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # LB 을 NLB 로 생성 (default: classic)

spec:
  ports:
    - name: web-port
      port: 80
      targetPort: 80
  selector:
    app: web-server
  type: LoadBalancer
